### PR TITLE
Add license to code files

### PR DESCRIPTION
**Pull request by gauravgahlot**

### CODE REVIEW

**Comment by sahil-lakhwani** [comment]
Should the headers also be in the other files such as release.sh ?

**Comment by PrasadG193** [comment]
@gauravgahlot should we add headers in .sh files as well?

**Comment by gauravgahlot** [comment]
Sure we can. But is it a standard practice?

**Comment by PrasadG193** [comment]
@gauravgahlot , yes, same is followed in K8s repo https://github.com/kubernetes/kubernetes/blob/master/hack/build-go.sh

**Comment by gauravgahlot** [comment]
Cool, I will update the files then.

**Review by sahil-lakhwani — APPROVED** [review]

**Review by sahil-lakhwani — APPROVED** [review]

**Pull request merged**
